- hosts: master
  become: yes
  become_method: sudo
  tasks:
  - name: Remove official mesos
    dnf:
      name: mesos
      state: absent
  - name: Install packages
    dnf: name={{ item }} state=latest
    with_items:
      - wget
      - git
      - tar
      - docker
      - libcurl-devel
      - apr-devel
      - java-devel
      - maven
      - cyrus-sasl-devel
      - subversion-devel
  - shell: |
      mkdir cluster &&
      cd cluster &&

      if [ ! -d mesos-1.1.0 ]
      then
        wget http://www.apache.org/dist/mesos/1.1.0/mesos-1.1.0.tar.gz &&
        tar xf mesos-1.1.0.tar.gz
      fi &&

      cd mesos-1.1.0 &&
      ./bootstrap &&
      mkdir build &&
      cd build &&
      ../configure &&
      make &&
      make check &&
      make install
